set term=screen-256color
set mouse=a

" 自动安装 vim-plug
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --insecure --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

" vim-plug 插件列表
call plug#begin('~/.vim/plugged')
""""""""""""""""""""""""""""""""""""""""""""""""""
" 主题
"Plug 'altercation/vim-colors-solarized'
"Plug 'tomasr/molokai'
"Plug 'vim-scripts/phd'
Plug 'rafi/awesome-vim-colorschemes'

" 基本设置
Plug 'tpope/vim-sensible'

" 状态栏
Plug 'Lokaltog/vim-powerline', {'branch': 'develop'}

" C++ 语法高亮
Plug 'octol/vim-cpp-enhanced-highlight'

" 显示缩进
"Plug 'nathanaelkane/vim-indent-guides'
Plug 'thaerkh/vim-indentguides'

" 切换头/源文件
Plug 'lljbash/vim-fswitch'

" 打标签：mx  跳转：'x  最后一次更改：'.  来回跳：''
Plug 'kshenoy/vim-signature'

" C++ 文件大纲  依赖 ctags
Plug 'majutsushi/tagbar'

" 全局搜索
"Plug 'dyng/ctrlsf.vim'

" 多光标，选中任意文本后，使用 <C-n> 和 <C-p> 找到下一个匹配的字符
Plug 'terryma/vim-multiple-cursors'

" <Leader>cc 加注释; <Leader>cu 解注释; <Leader>c<space> 切注释; <Leader>cy 复制+注释
Plug 'scrooloose/nerdcommenter'

" 用 tab 进行所有类型的补全
"Plug 'ervandew/supertab'

" 各种 snippets
Plug 'SirVer/ultisnips'
"Plug 'honza/vim-snippets'

" <Leader>PP 由 C++ 接口快速生成实现框架，
"Plug 'derekwyatt/vim-protodef'
Plug 'Pomakhin/vim-protodef-custom'

" 文件树
"Plug 'scrooloose/nerdtree'
"Plug 'Xuyuanp/nerdtree-git-plugin'

" 多标签管理
"Plug 'fholgado/minibufexpl.vim'

" 智能范围选择
Plug 'gcmt/wildfire.vim'

" <Leader><Leader> 开头的快速跳转
Plug 'Lokaltog/vim-easymotion'

" 括号自动补全
"Plug 'Raimondi/delimitMate'
"Plug 'jiangmiao/auto-pairs'
" now using coc-pairs

" 括号环绕、编辑、取消
Plug 'tpope/vim-surround'

" fzf
"Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf'

" 自动进入paste模式
Plug 'ConradIrwin/vim-bracketed-paste'

" 支持多种版本管理系统的 diff 显示
if has('nvim') || has('patch-8.0.902')
  Plug 'mhinz/vim-signify'
else
  Plug 'mhinz/vim-signify', { 'branch': 'legacy' }
endif

" 根据编码显示颜色
Plug 'lilydjwg/colorizer'

" Terminal
Plug 'voldikss/vim-floaterm'

" 自动补全框架，需要 node, 用 CocInstall 安装插件
Plug 'neoclide/coc.nvim', {'branch': 'release'}

" 基于 LSP 的 C++ 高亮
Plug 'jackguo380/vim-lsp-cxx-highlight'

""""""""""""""""""""""""""""""""""""""""""""""""""
call plug#end()

" 定义快捷键的前缀，即<Leader>
let mapleader=";"

" 开启文件类型侦测
filetype on
" 根据侦测到的不同类型加载对应的插件
filetype plugin on

" 自适应不同语言的智能缩进
filetype indent on
"set cino+=g0N-s
" 将制表符扩展为空格
set expandtab
" 设置编辑时制表符占用空格数
set tabstop=2
" 设置格式化时制表符占用空格数
set shiftwidth=2
" 让 vim 把连续数量的空格视为一个制表符
set softtabstop=2

" Google
""""""""""""""""""""""""""""""""""""""""""""""""""

" Load the default google configuration
source /usr/share/vim/google/google.vim

" Automatically change the working path to the path of the current file
"autocmd BufNewFile,BufEnter * silent! lcd %:p:h
" Instead, mapping for quick directory change
nnoremap <leader><leader>. :lcd %:p:h<CR>:pwd<CR>
nnoremap <leader>.. :lcd ..<CR>:pwd<CR>

" Load the blaze plugins, with the ;b prefix on all commands.
" Thus, to Blaze build, you can do <leader>bb.
" Since we've set the mapleader to ';' above, this should be ;bb in practice
Glug blaze plugin[mappings]='<leader>b'

" Load the code formatting plugin. We first load the open-source version. Then,
" we load the internal google settings. Then, we automatically enable formatting
" when we write the file for Go, BUILD, proto, and c/cpp files.
" Use :h codefmt-google or :h codefmt for more details.
Glug codefmt
Glug codefmt-google

" Wrap autocmds inside an augroup to protect against reloading this script.
" For more details, see:
" http://learnvimscriptthehardway.stevelosh.com/chapters/14.html
augroup autoformat
  autocmd!
  " Autoformat BUILD files on write.
  autocmd FileType bzl AutoFormatBuffer buildifier
  " Autoformat go files on write.
  autocmd FileType go AutoFormatBuffer gofmt
  " Autoformat proto files on write.
  autocmd FileType proto AutoFormatBuffer clang-format
  " Autoformat c and c++ files on write.
  autocmd FileType c,cpp AutoFormatBuffer clang-format
augroup END

" Load the Related Files plugin. Use :h relatedfiles for more details
Glug relatedfiles
nnoremap <unique> <leader>rf :RelatedFilesWindow<CR>

" Load piper integration (http://go/VimPerforce).
Glug piper plugin[mappings]

" Load Critique integration. Use :h critique for more details.
Glug critique plugin[mappings]

" Load the ultisnips plugin (http://go/ultisnips).
" Note: this requires installing the upstream ultisnips plugin from
" https://github.com/SirVer/ultisnips.
Glug ultisnips-google

""""""""""""""""""""""""""""""""""""""""""""""""""

" 定义快捷键到行首和行尾
nmap LB 0
nmap LE $
" 设置快捷键将选中文本块复制至系统剪贴板
vnoremap <Leader>y "+y
nnoremap <Leader>y "+y
" 设置快捷键将系统剪贴板内容粘贴至 vim
"nmap <Leader>p "+p
" 定义快捷键关闭当前分割窗口
"nmap <Leader>q :q<CR>
" 定义快捷键保存当前窗口内容
nmap <Leader>w :w<CR>
" 定义快捷键保存所有窗口内容并退出 vim
nmap <Leader>WQ :wa<CR>:q<CR>
" 不做任何保存，直接退出 vim
nmap <Leader>Q :qa!<CR>
" 依次遍历子窗口
nnoremap <Leader>nw <C-W><C-W>
" 跳转至右方的窗口
nnoremap <Leader>lw <C-W>l
" 跳转至左方的窗口
nnoremap <Leader>hw <C-W>h
" 跳转至上方的子窗口
nnoremap <Leader>kw <C-W>k
" 跳转至下方的子窗口
nnoremap <Leader>jw <C-W>j
" 定义快捷键在结对符之间跳转
nmap <Leader>M %

" 让配置变更立即生效
"autocmd BufWritePost $MYVIMRC source $MYVIMRC

" 搜索时大小写不敏感
"set ignorecase
" 关闭兼容模式
set nocompatible

" 禁止光标闪烁
set gcr=a:block-blinkon0
" 禁止显示滚动条
set guioptions-=l
set guioptions-=L
set guioptions-=r
set guioptions-=R
" 禁止显示菜单和工具条
set guioptions-=m
set guioptions-=T

" 开启行号显示
set number
" 高亮显示当前行/列
set cursorline
hi CursorLine cterm=NONE ctermbg=darkred ctermfg=white guibg=darkred guifg=white
" set cursorcolumn
" 高亮显示搜索结果
set hlsearch

" 设置 gvim 显示字体
"set guifont=YaHei\ Consolas\ Hybrid\ 11.5

" 禁止折行
"set nowrap

" 开启语法高亮功能
syntax enable
" 允许用指定语法高亮配色方案替换默认方案
syntax on

" 配色方案
"set background=dark
"colorscheme solarized
colorscheme molokai
"colorscheme molokayo
"colorscheme phd

" 自定义高亮配置应在此之后
au ColorScheme * call Highlight()
function! Highlight() abort
    if (g:colors_name =~ "molokai")
        hi! CocMenuSel ctermbg=237 guibg=#13354A
        hi! CocPumSearch ctermfg=48 guifg=#00ff87
        "hi! CocFloating guibg=#151515 guifg=#808080 ctermbg=233 ctermfg=244
    endif
    exec 'hi SignifySignAdd guifg=green ctermfg=green' .
                \' guibg=' . synIDattr(synIDtrans(hlID('SignColumn')), 'bg', 'gui') .
                \' ctermbg=' . synIDattr(synIDtrans(hlID('SignColumn')), 'bg', 'cterm')
    exec 'hi SignifySignDelete guifg=red ctermfg=red' .
                \' guibg=' . synIDattr(synIDtrans(hlID('SignColumn')), 'bg', 'gui') .
                \' ctermbg=' . synIDattr(synIDtrans(hlID('SignColumn')), 'bg', 'cterm')
    exec 'hi SignifySignChange guifg=yellow ctermfg=yellow' .
                \' guibg=' . synIDattr(synIDtrans(hlID('SignColumn')), 'bg', 'gui') .
                \' ctermbg=' . synIDattr(synIDtrans(hlID('SignColumn')), 'bg', 'cterm')
endfunction
call Highlight()

" 基于缩进或语法进行代码折叠
"set foldmethod=indent
set foldmethod=syntax
" 启动 vim 时关闭折叠代码
set nofoldenable

" 切换粘贴模式
set pastetoggle=<F9>
" 禁止系统剪贴板
"set clipboard=exclude:.*
" 默认使用系统剪贴板
"set clipboard^=unnamed,unnamedplus
"nnoremap <leader>p :<c-u>put +<cr>

" 禁止鼠标中键功能
map <MiddleMouse> <Nop>
map! <MiddleMouse> <Nop>
map <2-MiddleMouse> <Nop>
map! <2-MiddleMouse> <Nop>
map <3-MiddleMouse> <Nop>
map! <3-MiddleMouse> <Nop>
map <4-MiddleMouse> <Nop>
map! <4-MiddleMouse> <Nop>

" 设置状态栏
let g:Powerline_colorscheme='solarized256'

"" C++ 高亮设置
let g:cpp_posix_standard = 1
let g:cpp_concepts_highlight = 1
let c_no_curly_error=1

" Doxygen 识别为 C++
au! BufNewFile,BufRead *.dox setf cpp
" Justfile 识别为 Makefile
au BufNewFile,BufRead justfile,Justfile setf make

"" 显示缩进设置
" 随 vim 自启动
"let g:indent_guides_enable_on_vim_startup=1
" 从第二层开始可视化显示缩进
"let g:indent_guides_start_level=2
" 色块宽度
"let g:indent_guides_guide_size=1
" 快捷键 i 开/关缩进可视化
":nmap <silent> <Leader>i <Plug>IndentGuidesToggle
let g:indentguides_spacechar = '┆'
let g:indentguides_tabchar = '|'

"" *.cpp 和 *.h 间切换
nnoremap <silent> <Leader>sw :FSHere<cr>

"" tagbar 设置
nnoremap <Leader>t :TagbarToggle<CR>
" 启动时自动focus
let g:tagbar_autofocus = 1

"" floaterm 设置
let g:floaterm_keymap_new    = '<F6>'
let g:floaterm_keymap_prev   = '<F7>'
let g:floaterm_keymap_next   = '<F8>'
let g:floaterm_keymap_toggle = '<F5>'
autocmd QuitPre * :FloatermKill!

"" ycm 设置
"let g:ycm_global_ycm_extra_conf = '~/.vim/.ycm_extra_conf.py'
"let g:ycm_confirm_extra_conf = 0
"let g:ycm_add_preview_to_completeopt = 0
"let g:ycm_show_diagnostics_ui = 1
"let g:ycm_server_log_level = 'info'
"let g:ycm_min_num_of_chars_for_completion = 2
"let g:ycm_min_num_identifier_candidate_chars = 2
"let g:ycm_collect_identifiers_from_comments_and_strings = 1
"let g:ycm_complete_in_comments = 1
"let g:ycm_complete_in_strings = 1
"set completeopt=menu,menuone
"let g:ycm_key_list_select_completion = ['<C-n>']
"let g:ycm_key_list_previous_completion = ['<C-p>']
"let g:ycm_key_list_stop_completion = ['<C-y>', '<UP>', '<DOWN>']
"let g:SuperTabDefaultCompletionType = '<C-n>'
" better key bindings for UltiSnipsExpandTrigger
"let g:UltiSnipsExpandTrigger = "<tab>"
"let g:UltiSnipsJumpForwardTrigger = "<tab>"
"let g:UltiSnipsJumpBackwardTrigger = "<s-tab>"
"let g:ycm_seed_identifiers_with_syntax = 1
"let g:ycm_collect_identifiers_from_tags_files = 1
"let g:EclimCompletionMethod = 'omnifunc'
"nnoremap <Leader>g :YcmCompleter GoToDefinitionElseDeclaration<CR>
"nnoremap <Leader>f :YcmCompleter FixIt<CR>
"let g:ycm_semantic_triggers =  {
"            \ 'c,cpp,python,java,go,erlang,perl': ['re!\w{2}'],
"            \ 'cs,lua,javascript': ['re!\w{2}'],
"            \ }

"" 文件树设置
"" <Leader>N 打开/关闭
"nnoremap <silent> <Leader>n :NERDTreeToggle<CR>
"" 当不带参数打开Vim时自动加载项目树
"autocmd StdinReadPre * let s:std_in=1
"autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | NERDTree | endif
"" 当所有文件关闭时关闭项目树窗格
"autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTreeType") && b:NERDTreeType == "primary") | q | endif
"" 不显示这些文件
"let NERDTreeIgnore=['\.pyc$', '\~$', 'node_modules'] "ignore files in NERDTree
"" 不显示项目树上额外的信息，例如帮助、提示什么的
"let NERDTreeMinimalUI=1


"" coc 设置

" TextEdit might fail if hidden is not set.
set hidden

" Some servers have issues with backup files, see #649.
set nobackup
set nowritebackup

" Give more space for displaying messages.
set cmdheight=1

" Having longer updatetime (default is 4000 ms = 4 s) leads to noticeable
" delays and poor user experience.
set updatetime=300

" Don't pass messages to |ins-completion-menu|.
set shortmess+=c

" Always show the signcolumn, otherwise it would shift the text each time
" diagnostics appear/become resolved.
set signcolumn=yes

" Use tab for trigger completion with characters ahead and navigate.
" NOTE: Use command ':verbose imap <tab>' to make sure tab is not mapped by
" other plugin before putting this into your config.
let g:UltiSnipsExpandTrigger = "<nop>"
function! CheckBackSpace() abort
  let col = col('.') - 1
  return !col || getline('.')[col - 1]  =~ '\s'
endfunction
" Insert <tab> when previous text is space, refresh completion if not.
inoremap <silent><expr> <TAB>
  \ coc#pum#visible() ? coc#pum#next(1):
  \ CheckBackSpace() ? "\<Tab>" :
  \ coc#refresh()
inoremap <expr><S-TAB> coc#pum#visible() ? coc#pum#prev(1) : "\<C-h>"

" Use <c-space> to trigger completion.
if has('nvim')
  inoremap <silent><expr> <c-space> coc#refresh()
else
  inoremap <silent><expr> <c-@> coc#refresh()
endif

" Use <cr> to confirm completion, `<C-g>u` means break undo chain at current
" position. Coc only does snippet and additional edit on confirm.
inoremap <silent><expr> <cr> coc#pum#visible() ? coc#_select_confirm() : "\<C-g>u\<CR>\<c-r>=coc#on_enter()\<CR>"
"inoremap <silent><expr> <cr> coc#pum#visible() && coc#pum#info()['index'] != -1 ? coc#pum#confirm() : "\<C-g>u\<CR>\<c-r>=coc#on_enter()\<CR>"

" Use `[g` and `]g` to navigate diagnostics
nmap <silent> [g <Plug>(coc-diagnostic-prev)
nmap <silent> ]g <Plug>(coc-diagnostic-next)

" GoTo code navigation.
nmap <silent> gd <Plug>(coc-definition)
nmap <silent> gy <Plug>(coc-type-definition)
nmap <silent> gi <Plug>(coc-implementation)
nmap <silent> gr <Plug>(coc-references)

" Use K to show documentation in preview window.
nnoremap <silent> K :call <SID>show_documentation()<CR>

function! s:show_documentation()
  if (index(['vim','help'], &filetype) >= 0)
    execute 'h '.expand('<cword>')
  else
    call CocAction('doHover')
  endif
endfunction

" Highlight the symbol and its references when holding the cursor.
autocmd CursorHold * silent call CocActionAsync('highlight')

" Symbol renaming.
nmap <leader>rn <Plug>(coc-rename)

" Formatting selected code.
xmap <leader>f  <Plug>(coc-format-selected)
nmap <leader>f  <Plug>(coc-format-selected)

augroup mygroup
  autocmd!
  " Setup formatexpr specified filetype(s).
  autocmd FileType typescript,json setl formatexpr=CocAction('formatSelected')
  " Update signature help on jump placeholder.
  autocmd User CocJumpPlaceholder call CocActionAsync('showSignatureHelp')
augroup end

" Applying codeAction to the selected region.
" Example: `<leader>aap` for current paragraph
xmap <leader>a  <Plug>(coc-codeaction-selected)
nmap <leader>a  <Plug>(coc-codeaction-selected)

" Remap keys for applying codeAction to the current line.
nmap <leader>ac  <Plug>(coc-codeaction)
" Apply AutoFix to problem on the current line.
nmap <leader>qf  <Plug>(coc-fix-current)

" Introduce function text object
" NOTE: Requires 'textDocument.documentSymbol' support from the language server.
xmap if <Plug>(coc-funcobj-i)
xmap af <Plug>(coc-funcobj-a)
omap if <Plug>(coc-funcobj-i)
omap af <Plug>(coc-funcobj-a)

" Use <TAB> for selections ranges.
" NOTE: Requires 'textDocument/selectionRange' support from the language server.
" coc-tsserver, coc-python are the examples of servers that support it.
nmap <silent> <TAB> <Plug>(coc-range-select)
xmap <silent> <TAB> <Plug>(coc-range-select)

" Add `:Format` command to format current buffer.
command! -nargs=0 Format :call CocAction('format')

" Add `:Fold` command to fold current buffer.
command! -nargs=? Fold :call     CocAction('fold', <f-args>)

" Add `:OR` command for organize imports of the current buffer.
command! -nargs=0 OR   :call     CocAction('runCommand', 'editor.action.organizeImport')

" Add (Neo)Vim's native statusline support.
" NOTE: Please see `:h coc-status` for integrations with external plugins that
" provide custom statusline: lightline.vim, vim-airline.
set statusline^=%{coc#status()}%{get(b:,'coc_current_function','')}

" Mappings using CoCList:
" Call CocList.
nnoremap <silent> <space><space>  :<C-u>CocList<cr>
" Show all diagnostics.
nnoremap <silent> <space>a  :<C-u>CocList diagnostics<cr>
" Manage extensions.
nnoremap <silent> <space>e  :<C-u>CocList extensions<cr>
" Show commands.
nnoremap <silent> <space>c  :<C-u>CocList commands<cr>
" Find symbol of current document.
nnoremap <silent> <space>o  :<C-u>CocList outline<cr>
" Search workspace symbols.
nnoremap <silent> <space>s  :<C-u>CocList -I symbols<cr>
" Do default action for next item.
nnoremap <silent> <space>j  :<C-u>CocNext<CR>
" Do default action for previous item.
nnoremap <silent> <space>k  :<C-u>CocPrev<CR>
" Resume latest coc list.
nnoremap <silent> <space>p  :<C-u>CocListResume<CR>
" Enhanced search
nnoremap <silent> <space>/  :<C-u>CocList words<CR>
" Grep in current cwd.
nnoremap <silent> <space>g  :<C-u>CocList grep<CR>
" Open file.
nnoremap <silent> <space>n  :<C-u>CocList files<cr>
" Show buffers.
nnoremap <silent> <space>b  :<C-u>CocList buffers<cr>
" Mappings using coc-yank
nnoremap <silent> <space>y  :<C-u>CocList -A --normal yank<cr>

" grep word under cursor
command! -nargs=+ -complete=custom,s:GrepArgs Rg exe 'CocList grep '.<q-args>

function! s:GrepArgs(...)
  let list = ['-S', '-smartcase', '-i', '-ignorecase', '-w', '-word',
        \ '-e', '-regex', '-u', '-skip-vcs-ignores', '-t', '-extension']
  return join(list, "\n")
endfunction

" Keymapping for grep word under cursor with interactive mode
nnoremap <silent> <Leader>cf :exe 'CocList -I --input='.expand('<cword>').' grep'<CR>

" auto fix by clangd
nnoremap <leader>f :CocList --input=fix actions<cr>


"" coc-fzf-preview mappings
nmap <Leader>f [fzf-p]
xmap <Leader>f [fzf-p]

nnoremap <silent> [fzf-p]p     :<C-u>CocCommand fzf-preview.FromResources project_mru git<CR>
nnoremap <silent> [fzf-p]gs    :<C-u>CocCommand fzf-preview.GitStatus<CR>
nnoremap <silent> [fzf-p]ga    :<C-u>CocCommand fzf-preview.GitActions<CR>
nnoremap <silent> [fzf-p]b     :<C-u>CocCommand fzf-preview.Buffers<CR>
nnoremap <silent> [fzf-p]B     :<C-u>CocCommand fzf-preview.AllBuffers<CR>
nnoremap <silent> [fzf-p]o     :<C-u>CocCommand fzf-preview.FromResources buffer project_mru<CR>
nnoremap <silent> [fzf-p]<C-o> :<C-u>CocCommand fzf-preview.Jumps<CR>
nnoremap <silent> [fzf-p]g;    :<C-u>CocCommand fzf-preview.Changes<CR>
nnoremap <silent> [fzf-p]/     :<C-u>CocCommand fzf-preview.Lines --add-fzf-arg=--no-sort --add-fzf-arg=--query="'"<CR>
nnoremap <silent> [fzf-p]*     :<C-u>CocCommand fzf-preview.Lines --add-fzf-arg=--no-sort --add-fzf-arg=--query="'<C-r>=expand('<cword>')<CR>"<CR>
nnoremap          [fzf-p]gr    :<C-u>CocCommand fzf-preview.ProjectGrep<Space>
xnoremap          [fzf-p]gr    "sy:CocCommand   fzf-preview.ProjectGrep<Space>-F<Space>"<C-r>=substitute(substitute(@s, '\n', '', 'g'), '/', '\\/', 'g')<CR>"
nnoremap <silent> [fzf-p]t     :<C-u>CocCommand fzf-preview.BufferTags<CR>
nnoremap <silent> [fzf-p]q     :<C-u>CocCommand fzf-preview.QuickFix<CR>
nnoremap <silent> [fzf-p]l     :<C-u>CocCommand fzf-preview.LocationList<CR>
nnoremap <silent> [fzf-p]n     :<C-u>CocCommand fzf-preview.ProjectFiles<CR>
nnoremap <silent> [fzf-p]N     :<C-u>CocCommand fzf-preview.DirectoryFiles<CR>
nnoremap <silent> [fzf-p]gn     :<C-u>CocCommand fzf-preview.GitFiles<CR>

"" coc-typos mappings
" Move to next misspelled word after the cursor, 'wrapscan' applies.
nmap ]s <Plug>(coc-typos-next)
" Move to previous misspelled word after the cursor, 'wrapscan' applies.
nmap [s <Plug>(coc-typos-prev)
" Fix typo at cursor position
nmap z= <Plug>(coc-typos-fix)
