--- 使用 which-key 维护所有按键映射
return {
  {
    "folke/which-key.nvim",
    event = "VeryLazy",
    dependencies = {
      "echasnovski/mini.icons",
      "nvim-tree/nvim-web-devicons",
    },
    keys = {
      {
        "<leader>?",
        function()
          require("which-key").show({ global = true })
        end,
        desc = "Keymaps (which-key)",
      },
    },
    opts = {
      win = {
        no_overlap = false,
      },
      spec = {
        { "<Leader>", group = "Leader", mode = {"n", "x", "o"} },
        {
          mode = { "n", "v" },
          { "<Leader>.", group = "Working directory" },
          { "<Leader>..", "<cmd>lcd ..<cr><cmd>pwd<cr>", desc = "cd .." },
          { "<Leader>.<cr>", "<cmd>lcd %:p:h<cr><cmd>pwd<cr>", desc = "Set cwd to buffer" },
          { "<Leader>q", "<cmd>qa<cr>", desc = "Quit vim" },
          { "<Leader>Q", "<cmd>qa!<cr>", desc = "Force quit" },
          { "<Leader>w", "<cmd>w<cr>", desc = "Save buffer" },
          { "<Leader>W", "<cmd>wa<cr>", desc = "Save all" },
        },
        -- comes from unimpaired-which-key normal_mode
        {
          { "<P", desc = "Paste before linewise, decreasing indent" },
          { "<p", desc = "Paste after linewise, decreasing indent" },
          { "<s", group = "Enable" },
          { "<sb", desc = "Enable background" },
          { "<sc", desc = "Enable cursorline" },
          { "<sd", desc = "Enable diff" },
          { "<sh", desc = "Enable hlsearch" },
          { "<si", desc = "Enable ignorecase" },
          { "<sl", desc = "Enable list" },
          { "<sn", desc = "Enable number" },
          { "<sr", desc = "Enable relativenumber" },
          { "<ss", desc = "Enable spell" },
          { "<st", desc = "Enable colorcolumn" },
          { "<su", desc = "Enable cursorcolumn" },
          { "<sv", desc = "Enable virtualedit" },
          { "<sw", desc = "Enable wrap" },
          { "<sx", desc = "Enable cursorline + cursorcolumn" },
          { "=P", desc = "Paste before linewise, reindenting" },
          { "=p", desc = "Paste after linewise, reindenting" },
          { "=s", group = "Toggle" },
          { "=sb", desc = "Toggle background" },
          { "=sc", desc = "Toggle cursorline" },
          { "=sd", desc = "Toggle diff" },
          { "=sh", desc = "Toggle hlsearch" },
          { "=si", desc = "Toggle ignorecase" },
          { "=sl", desc = "Toggle list" },
          { "=sn", desc = "Toggle number" },
          { "=sr", desc = "Toggle relativenumber" },
          { "=ss", desc = "Toggle spell" },
          { "=st", desc = "Toggle colorcolumn" },
          { "=su", desc = "Toggle cursorcolumn" },
          { "=sv", desc = "Toggle virtualedit" },
          { "=sw", desc = "Toggle wrap" },
          { "=sx", desc = "Toggle cursorline + cursorcolumn" },
          { ">P", desc = "Paste before linewise, increasing indent" },
          { ">p", desc = "Paste after linewise, increasing indent" },
          { ">s", group = "Disable" },
          { ">sb", desc = "Disable background" },
          { ">sc", desc = "Disable cursorline" },
          { ">sd", desc = "Disable diff" },
          { ">sh", desc = "Disable hlsearch" },
          { ">si", desc = "Disable ignorecase" },
          { ">sl", desc = "Disable list" },
          { ">sn", desc = "Disable number" },
          { ">sr", desc = "Disable relativenumber" },
          { ">ss", desc = "Disable spell" },
          { ">st", desc = "Disable colorcolumn" },
          { ">su", desc = "Disable cursorcolumn" },
          { ">sv", desc = "Disable virtualedit" },
          { ">sw", desc = "Disable wrap" },
          { ">sx", desc = "Disable cursorline + cursorcolumn" },
          { "[", group = "Previous" },
          { "[<C-L>", desc = "Last entry in prev file in locationlist" },
          { "[<C-Q>", desc = "Last entry in prev file in quickfixlist" },
          { "[<C-T>", desc = "Prev matching tag in preview window" },
          { "[<Space>", desc = "Add blank lines above" },
          { "[A", desc = "First file in the argument list." },
          { "[B", desc = "First buffer in buffer list" },
          { "[L", desc = "First locationlist entry" },
          { "[P", desc = "Put above" },
          { "[Q", desc = "First quickfix entry" },
          { "[T", desc = "First matching tag" },
          { "[a", desc = "Prev file in argument list" },
          { "[b", desc = "Prev buffer in buffer list" },
          { "[e", desc = "Exchange line with lines above" },
          { "[f", desc = "Prev file in directory" },
          { "[l", desc = "Prev locationlist entry" },
          { "[n", desc = "Prev prev conflict/diff/hunk" },
          { "[o", group = "Enable" },
          { "[ob", desc = "Enable background" },
          { "[oc", desc = "Enable cursorline" },
          { "[od", desc = "Enable diff" },
          { "[oh", desc = "Enable hlsearch" },
          { "[oi", desc = "Enable ignorecase" },
          { "[ol", desc = "Enable list" },
          { "[on", desc = "Enable number" },
          { "[or", desc = "Enable relativenumber" },
          { "[os", desc = "Enable spell" },
          { "[ot", desc = "Enable colorcolumn" },
          { "[ou", desc = "Enable cursorcolumn" },
          { "[ov", desc = "Enable virtualedit" },
          { "[ow", desc = "Enable wrap" },
          { "[ox", desc = "Enable cursorline + cursorcolumn" },
          { "[p", desc = "Put above" },
          { "[q", desc = "Prev quickfix entry" },
          { "[t", desc = "Prev matching tag" },
          { "]", group = "Next" },
          { "]<C-L>", desc = "First entry in next file in locationlist" },
          { "]<C-Q>", desc = "First entry in next file in quickfixlist" },
          { "]<C-T>", desc = "Next matching tag in preview window" },
          { "]<Space>", desc = "Add blank lines below" },
          { "]A", desc = "Last file in the argument list." },
          { "]B", desc = "Last buffer in buffer list" },
          { "]L", desc = "Last locationlist entry" },
          { "]P", desc = "Put below" },
          { "]Q", desc = "Last quickfix entry" },
          { "]T", desc = "Last matching tag" },
          { "]a", desc = "Next file in argument list" },
          { "]b", desc = "Next buffer in buffer list" },
          { "]e", desc = "Exchange line with lines below" },
          { "]f", desc = "Next file in directory" },
          { "]l", desc = "Next locationlist entry" },
          { "]n", desc = "Next prev conflict/diff/hunk" },
          { "]o", group = "Disable" },
          { "]ob", desc = "Disable background" },
          { "]oc", desc = "Disable cursorline" },
          { "]od", desc = "Disable diff" },
          { "]oh", desc = "Disable hlsearch" },
          { "]oi", desc = "Disable ignorecase" },
          { "]ol", desc = "Disable list" },
          { "]on", desc = "Disable number" },
          { "]or", desc = "Disable relativenumber" },
          { "]os", desc = "Disable spell" },
          { "]ot", desc = "Disable colorcolumn" },
          { "]ou", desc = "Disable cursorcolumn" },
          { "]ov", desc = "Disable virtualedit" },
          { "]ow", desc = "Disable wrap" },
          { "]ox", desc = "Disable cursorline + cursorcolumn" },
          { "]p", desc = "Put below" },
          { "]q", desc = "Next quickfix entry" },
          { "]t", desc = "Next matching tag" },
          { "yo", group = "Toggle" },
          { "yob", desc = "Toggle background" },
          { "yoc", desc = "Toggle cursorline" },
          { "yod", desc = "Toggle diff" },
          { "yoh", desc = "Toggle hlsearch" },
          { "yoi", desc = "Toggle ignorecase" },
          { "yol", desc = "Toggle list" },
          { "yon", desc = "Toggle number" },
          { "yor", desc = "Toggle relativenumber" },
          { "yos", desc = "Toggle spell" },
          { "yot", desc = "Toggle colorcolumn" },
          { "you", desc = "Toggle cursorcolumn" },
          { "yov", desc = "Toggle virtualedit" },
          { "yow", desc = "Toggle wrap" },
          { "yox", desc = "Toggle cursorline + cursorcolumn" },
        },
        -- comes from unimpaired-which-key normal_and_visual_mode
        {
          mode = { "n", "v" },
          { "[C", desc = "C String encode" },
          { "[CC", desc = "C String encode line" },
          { "[u", desc = "URL encode" },
          { "[uu", desc = "URL encode line" },
          { "[x", desc = "XML encode" },
          { "[xx", desc = "XML encode line" },
          { "[y", desc = "C String encode" },
          { "[yy", desc = "C String encode line" },
          { "]C", desc = "C String decode" },
          { "]CC", desc = "C String decode line" },
          { "]u", desc = "URL decode" },
          { "]uu", desc = "URL decode line" },
          { "]x", desc = "XML decode" },
          { "]xx", desc = "XML decode line" },
          { "]y", desc = "C String decode" },
          { "]yy", desc = "C String decode line" },
        },
      },
    },
  },

  -- unimpaired-which-key is now registered manually in which-key v3 API
  {
    enabled = false,
    "afreakk/unimpaired-which-key.nvim",
    dependencies = {
      "tpope/vim-unimpaired",
      "folke/which-key.nvim",
    },
    config = function()
      local wk = require("which-key")
      local uwk = require("unimpaired-which-key")
      wk.register(uwk.normal_mode)
      wk.register(uwk.normal_and_visual_mode, { mode = { "n", "v" } })
    end,
  },
}
